/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahmd.maulidanngmail.com
 */
public class myTicket extends javax.swing.JFrame {

    /**
     * Creates new form myTicket
     */
    public myTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/wonderful.png"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Festival Kebudayaan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Tampilkan Tabel");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("My Ticket");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Nama Event", "Tempat", "Nomor Konfirmasi"
            }
        ));
        tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelData);
        if (tabelData.getColumnModel().getColumnCount() > 0) {
            tabelData.getColumnModel().getColumn(0).setHeaderValue("Tanggal");
            tabelData.getColumnModel().getColumn(1).setHeaderValue("Nama Event");
            tabelData.getColumnModel().getColumn(2).setHeaderValue("Tempat");
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 730, 290));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/kalender2.png"))); // NOI18N
        jLabel6.setText("Event Terdekat");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/search2.png"))); // NOI18N
        jLabel7.setText("Cari Provinsi ");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/home.png"))); // NOI18N
        jLabel15.setText("Home");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, -1, -1));

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/tiket.png"))); // NOI18N
        jLabel16.setText("My Tiket");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel16MousePressed(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/logout.png"))); // NOI18N
        jLabel5.setText("Keluar");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/homeBG.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        // TODO add your handling code here:
        this.dispose();
        eventTerdekat et = new eventTerdekat();
        et.setVisible(true);
        et.pack();
        et.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
        this.dispose();
        Main m = new Main();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        // TODO add your handling code here:
        this.dispose();
        Home et = new Home();
        et.setVisible(true);
        et.pack();
        et.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel15MousePressed

    private void jLabel16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MousePressed
        // TODO add your handling code here:
        this.dispose();
        myTicket et = new myTicket();
        et.setVisible(true);
        et.pack();
        et.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel16MousePressed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        DefaultTableModel datamodel = (DefaultTableModel) tabelData.getModel();
        ArrayList<String> nama = setorData.tanggal;
        ArrayList<String> NIK = setorData.namaEvent;
        ArrayList<String> asalDaerah = setorData.tempatDaerah;
        ArrayList<String> nomorPonsel = setorData.nomorPonsel;
        String[] namaArray = konversiArray(nama);
        String[] NIKArray = konversiArray(NIK);
        String[] asalDaerahArray = konversiArray(asalDaerah);
        String[] nomorPonselArray = konversiArray(nomorPonsel);
        tabelData.setAutoCreateColumnsFromModel(true);
        
        if (datamodel.getRowCount() < nama.size()) {
        for (int i = datamodel.getRowCount(); i < nama.size(); i++) {
            datamodel.addRow(new Object[]{null, null, null});
            }
        }

        for (int i = 0; i < nama.size(); i++) {
            datamodel.setValueAt(namaArray[i], i, 0); 
            datamodel.setValueAt(NIKArray[i], i, 1); 
            datamodel.setValueAt(asalDaerahArray[i], i, 2);
            datamodel.setValueAt(nomorPonselArray[i], i, 3);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
        int selectedRow = tabelData.getSelectedRow();
        String nilai = tabelData.getValueAt(selectedRow, 1).toString();
        switch(nilai){
            case "Musik Alam Fest":
                this.dispose();
                musikAlam newForm1 = new musikAlam();
                newForm1.setVisible(true);
                newForm1.setLocationRelativeTo(null);
                break;
            case  "Babukung":
                this.dispose();
                babukung newForm2 = new babukung();
                newForm2.setVisible(true);
                newForm2.setLocationRelativeTo(null);
                break;
            case "Iraw Tengkayu":
                this.dispose();
                irawTangakayu newForm3 = new irawTangakayu();
                newForm3.setVisible(true);
                break;
            case "Bamboo Rafting":
                this.dispose();
                bambooRafting newForm4 = new bambooRafting();
                newForm4.setVisible(true);
                break;
            case "Isen Mulang":
                this.dispose();
                budayaIsen newForm5 = new budayaIsen();
                newForm5.setVisible(true);
                break;
            case "Balikpapan Fest":
                this.dispose();
                balikpapanFest newForm6 = new balikpapanFest();
                newForm6.setVisible(true);
                break;
            case "Cap Go Meh":
                this.dispose();
                capGoMeh newForm7 = new capGoMeh();
                newForm7.setVisible(true);
                break;
            case "Gawia Soa":
                this.dispose();
                gawiaSoa newForm8 = new gawiaSoa();
                newForm8.setVisible(true);
                break;
            case "Hudoq Pekayangan":
                this.dispose();
                hudoqPekayangan newForm9 = new hudoqPekayangan();
                newForm9.setVisible(true);
                break;
            case "Lom Plai":
                this.dispose();
                lomPlai newForm10 = new lomPlai();
                newForm10.setVisible(true);
                break;
            case "Ruai Rindu":
                this.dispose();
                ruaiRindu newForm11 = new ruaiRindu();
                newForm11.setVisible(true);
                break;
        }
    }//GEN-LAST:event_tabelDataMouseClicked

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
        int pilihanUser = JOptionPane.showConfirmDialog(rootPane, "Anda yakin ingin keluar?","Konfirmasi", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        switch (pilihanUser) {
            case JOptionPane.YES_OPTION:
            this.dispose();
            loginForm rlf = new loginForm();
            rlf.setVisible(true);
            rlf.pack();
            rlf.setLocationRelativeTo(null);
            this.dispose();
            break;
            case JOptionPane.NO_OPTION:
            System.out.println("User chose No.");
            break;
            case JOptionPane.CANCEL_OPTION:
            System.out.println("User chose Cancel.");
            break;
            case JOptionPane.CLOSED_OPTION:
            System.out.println("User closed the dialog.");
            break;
        }
    }//GEN-LAST:event_jLabel5MousePressed
    public String[] konversiArray(ArrayList<String> data){
        String[] convertedArray = data.toArray(new String[0]);
        return convertedArray;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelData;
    // End of variables declaration//GEN-END:variables
}
